### ISSUE TITLE
[request] Please determine the plugin name?

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/infrakit.aws#13]
Please determine the plugin name?

* `flavor-combo`: https://github.com/docker/infrakit.aws/blob/0a5dbbf693e827bcf5467dbed1d327e79db24385/plugin/instance/cmd/main.go (actual code)
* `instance-aws`: https://github.com/docker/infrakit.aws/blob/4a747a820d00c54839575dac0f6b78e2de31f53c/README.md
* `aws`: https://github.com/docker/infrakit/blob/39a588db27a6fbf061b3ceb448a09d1a3453deb9/README.md

In actual code it is `flavor-combo`, but I guess it is not intended.

**Comment by wfarner** [comment]
You're correct, this was a sloppy copy-paste.  Thanks for the issue and patch!
